## Introduction to Object Oriented Programming (OOP) in Python

One of the proper approach to solve a progrraming problemsby creating an objects. This is known as Object Oriented Programming.

#### An object has two characteristics:

1. attributes (name, age, colour)

2. behaviour (learn, study, singing, dance)

In Python, the concept of OOP follow these things:

1. Inheritence

2. Encapsulation

3. Polymorphism

A class is a blueprint for the object

#### Object:

Blueprint of class or Instance of the class or physical entity 

#### Methods:

Part of class and can be called with object

#### Constructors:

Part of class  and can be called automatically when the  class is created

In [0]:
class classname:
  # some functions and variables
  # function -- used to perform the specific activity
  # variables -- Data(memory)

In [0]:
def test():
  print('Test() for function')
  return
test()

Test() for function


In [0]:
class demo:
  def test(self):
    print('test() for the class and method')
    return
obj=demo() #object creation
obj.test() #call for the method

test() for the class and method


In [0]:
class demo1:
  def fact(self,n):
    fact=1
    while(n!=0):
      fact=fact*n
      n=n-1
    return fact
p1=demo1()
print(p1.fact(5))

120


In [0]:
# Method
# def test(self,para1,para2)

In [0]:
class demo2:
  def accept(self,p1,p2):
    self.p2=p1
    self.p2=p2
    return
  def display(self):
    print('p1= ',p1)
    print('p2= ',p2)
c1=demo2()
c1.accept(10,20)
c1.display()

In [0]:
class demo2:
  def __init__(self,p1,p2):
    self.p1=p1
    self.p2=p2
  def add(self,p1,p2):
    return p1 + p2
c1=demo2(10,20)
print(c1.add(100,200))

300


In [0]:
lst =[1,2,3,4]
print(lst)

[1, 2, 3, 4]


In [0]:
import numpy as np
lst=[1,2,3,4]
array=np.array(lst)
print(array)

[1 2 3 4]


In [0]:
lst=[1,2,3,4]
array=np.array(lst)
print(array.shape)
print(array.dtype)

(4,)
int64


In [0]:
lst=[1.0,2.5,3.6,9.5]
array=np.array(lst)
print(array.shape)
print(array.dtype)

(4,)
float64


In [0]:
a1 = np.array([(1,2,3),(4,5,6)])
print(a1.shape)
a2 = np.array([(1,2),(3,4),(5,6)])
print(a2.shape)

(2, 3)
(3, 2)


In [0]:
#Re-shape the given array
#numpy.reshape(arrayname,reshape,order='C')
a1 = np.array([(1,2,3),(4,5,6)])
print(a1)
a1.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [0]:
#Append some data -- Horizontally
#hstack(array1,array2) -- will be automatically arranged in horizontal
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.hstack((a1,a2)))

[1 2 3 4 5 6]


In [0]:
#Append some data -- Vertical
#vstack(array1,array2) -- will be automatically arranged in vertically
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.vstack((a1,a2)))

[[1 2 3]
 [4 5 6]]


In [0]:
#Generate random numbers from NP
a1=np.random.normal(5,0.5,10)
print(a1)

[5.06034643 4.83692477 5.55682453 4.65149428 6.13791002 4.73393539
 4.54316984 5.03571784 4.4329181  5.59896929]


In [0]:
# numpy.zeros() and numpy.one()
# Generate an array with all zeros -- numpy.zeros()
# numpy.zeros(shape, dtype = float, order="C")
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [0]:
np.zeros((2,2),dtype=np.int16)

array([[0, 0],
       [0, 0]], dtype=int16)

In [0]:
#np.ones(shape,dtype=float,order='C')
np.ones((4,3),dtype=np.int64)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [0]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
print(A)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [0]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[2]=5
print(A)

[[1 1 1 1]
 [1 1 1 1]
 [5 5 5 5]
 [1 1 1 1]]


In [0]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[1][3]=14
np.asarray(A)[3][3]=16
print(A)

[[ 1  1  1  1]
 [ 1  1  1 14]
 [ 1  1  1  1]
 [ 1  1  1 16]]


In [0]:
#arrange() -- particular
#numpy.arrange(start,end,step)
#start -- value
#end -- value
#step -- Gap between one value to another value
import numpy as np
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
np.arange(1,100,9)

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [0]:
np.arange(2,20,2)
np.arange(1,25,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [0]:
# Indexing and Slicing of Numpy
a1=np.array([(1,2,3),(4,5,6)])
print(a1)

[[1 2 3]
 [4 5 6]]


In [0]:
a1=np.array([(1,2,3),(4,5,6)])
print('First Row: ',a1[1])

First Row:  [4 5 6]


In [0]:
a1=np.array([(1,2,3),(4,5,6)])
print('Second Row: ',a1[1])

Second Row:  [4 5 6]


In [0]:
a1=np.array([(1,2,3),(4,5,6)])
print('Slicing Column: ',a1[:,1])

Slicing Column:  [2 5]


In [0]:
a1=np.array([(1,2,3),(4,5,6)])
print('Slicing Last Column: ',a1[:,2])

Slicing Last Column:  [3 6]


In [0]:
a1=np.array([(1,2,3),(4,5,6)])
print('Row and Column',a1[1,:1])

Row and Column [4]


In [0]:
# Some math Operation on given random numbers
# Min    -- returns the least number
# Max    -- returns the large number
# Mean   -- Mean
# Median -- Medium
a1=np.random.normal(5,1,10)
print(a1)
print('Min value =',np.min(a1))
print('Max value =',np.max(a1))
print('Mean value =',np.mean(a1))
print('Median value =',np.median(a1))

[5.73938612 3.73238394 3.97617772 5.5922856  4.92458077 4.67043541
 7.68969661 4.61685297 4.63701129 5.67843143]
Min value = 3.7323839404284893
Max value = 7.689696612004672
Mean value = 5.125724184705975
Median value = 4.797508086659918


In [0]:
# Multiplication of 1D arrays
# numpy.dot(x,y) --
c1=np.array([1,2])
c2=np.array([4,5])
np.dot(c1,c2)

14

In [0]:
c1=np.array([(1,2),(3,4)])
c2=np.array([(3,4),(1,2)])
np.dot(c1,c2)

array([[ 5,  8],
       [13, 20]])

In [0]:
b1=np.array([(1,5),(6,9)])
b2=np.array([(1,3),(1,6)])
np.matmul(b1,b2)

array([[ 6, 33],
       [15, 72]])

### Pandas Basics

Python is one of the popular programming language for data analysis

Python is offering the Lib called Pandas used for importing and analyzing 

Pandas DataFrames

       Data Analysis with Python
       

In [0]:
import pandas as pd
dict={'Name':['Akash','Varma'],'EmailID':['akash@gmail.com','varma@gmail.com'],'MobileNumber':['84854','65956'],'Address':
     ['Hyd','Hyd']}
b=pd.DataFrame(dict)
print(b)

    Name          EmailID MobileNumber Address
0  Akash  akash@gmail.com        84854     Hyd
1  Varma  varma@gmail.com        65956     Hyd


In [0]:
b.index=['01','02']
print(b)

     Name          EmailID MobileNumber Address
01  Akash  akash@gmail.com        84854     Hyd
02  Varma  varma@gmail.com        65956     Hyd


In [0]:
# supermarket.csv -- Analysis (Which product having higher % of selling)
# Which products having least selling %
import pandas as pd
products=pd.read_csv('FileName.csv')
print(products)

In [0]:
import pandas as pd
product_sellingdata=pd.read_csv('FileName.csv',index_col=1)
print(product_sellingdata)

In [ ]:
#Create a series by passing a list of values
import pandas as pd
a = pd.Series([1,3,4,5,6,7])
print(a)